# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53cbe6bfc2dced8af35b8e637be9decdc3b061f9f7b99017789567e25f10b62524ca722d3a7e9decbc837c98aa154e52d6431babb6829d0780a2e9572c5d3ae8

test:
  secret_key_base: 97ba43b38e6790a9a6bdfd8785b54cd09b462d0fd6524ad98732d6214b210dc42a66faf50660cfd00700c2429b554901f579d3c6f19448526623d2ba2bbef9dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
